name: PR Checks (Main Branch Workflow)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch workflow
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we fetch the latest workflow from main

      - name: Fetch PR branch changes
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }} --depth=1

      - name: Check for banned keywords and files
        run: |
          BANNED_WORDS=("DELETE" "DROP")
          BANNED_FILES=("secrets.txt" "config.yaml")

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only origin/main origin/${{ github.event.pull_request.head.ref }})
          echo "Changed files: $CHANGED_FILES"

          for FILE in $CHANGED_FILES; do
            # Check if the file is in the banned files list
            for BANNED_FILE in "${BANNED_FILES[@]}"; do
              if [[ "$FILE" == "$BANNED_FILE" ]]; then
                echo "❌ Error: File '$FILE' is restricted and cannot be merged."
                exit 1
              fi
            done

            # Ensure the file exists before searching for keywords
            if [[ -f "$FILE" ]]; then
              for WORD in "${BANNED_WORDS[@]}"; do
                if grep -q "$WORD" "$FILE"; then
                  echo "❌ Error: Found banned keyword '$WORD' in file '$FILE'."
                  exit 1
                fi
              done
            fi

            # Check for Django migration files (inside any */migrations/ folder)
            if [[ "$FILE" =~ .*/migrations/[0-9]{4}_.*\.py$ ]]; then
              echo "⚠️ Warning: Django migration detected - '$FILE'."
              exit 1
            fi
          done

          echo "✅ No banned words or files found. Merge allowed."


# name: PR Keyword and File Check

# on:
#   pull_request:
#     branch:
#       - main
#     types: [opened, synchronize, reopened]

# jobs:
#   check-keywords-and-files:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0  # Ensures git history is available for git diff

#       - name: Check for banned keywords and files
#         run: |
#           BANNED_WORDS=("DELETE" "DROP")
#           BANNED_FILES=("secrets.txt" "config.yaml")

#           # Get list of changed files
#           CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }})
#           echo "Changed files: $CHANGED_FILES"

#           for FILE in $CHANGED_FILES; do
#             # Check if the file is in the banned files list
#             for BANNED_FILE in "${BANNED_FILES[@]}"; do
#               if [[ "$FILE" == "$BANNED_FILE" ]]; then
#                 echo "❌ Error: File '$FILE' is restricted and cannot be merged."
#                 exit 1
#               fi
#             done

#             # Check for banned keywords in each file
#             if [[ -f "$FILE" ]]; then  # Ensure the file exists before searching
#               for WORD in "${BANNED_WORDS[@]}"; do
#                 if grep -q "$WORD" "$FILE"; then
#                   echo "❌ Error: Found banned keyword '$WORD' in file '$FILE'."
#                   exit 1
#                 fi
#               done
#             fi

#             # Check for Django migration files (inside any */migrations/ folder)
#             if [[ "$FILE" =~ .*/migrations/[0-9]{4}_.*\.py$ ]]; then
#               echo "⚠️ Warning: Django migration detected - '$FILE'."
#               exit 1
#             fi
#           done

#           echo "✅ No banned words or files found, no Migration. Merge allowed."







