name: PR Keyword and File Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-keywords-and-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for banned keywords and files
        run: |
          BANNED_WORDS=("debug" "TODO" "fixme")
          BANNED_FILES=("secrets.txt" "config.yaml")

          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $CHANGED_FILES"

          for FILE in $CHANGED_FILES; do
            if [[ " ${BANNED_FILES[*]} " =~ " ${FILE} " ]]; then
              echo "❌ Error: File $FILE is restricted and cannot be merged."
              exit 1
            fi

            for WORD in "${BANNED_WORDS[@]}"; do
              if grep -q "$WORD" "$FILE"; then
                echo "❌ Error: Found banned keyword '$WORD' in file $FILE."
                exit 1
              fi
            done
          done
          
          echo "✅ No banned words or files found. Merge allowed."
