name: Protect GitHub Actions Workflows
on: [pull_request, push]

jobs:
  check-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow file was modified
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q ".github/workflows/"; then
            echo "❌ ERROR: GitHub Actions workflow files cannot be modified!"
            exit 1
          fi
