name: Protect GitHub Actions Workflows
on: [pull_request, push]

jobs:
  check-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow file was modified
        run: |
          BASE_BRANCH=$(git merge-base HEAD origin/main)
          if git diff --name-only $BASE_BRANCH | grep -q ".github/workflows/"; then
            echo "🚨 ERROR: Modifications to GitHub Action workflow files are not allowed!"
            exit 1
          fi
