name: Protect Workflow Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  protect-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Check for unauthorized workflow file changes
        run: |
          # Define the protected directory
          PROTECTED_DIR=".github/workflows/"

          # Get the list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }})

          # Initialize a flag to detect unauthorized changes
          UNAUTHORIZED_CHANGE=false

          # Check each changed file
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" == $PROTECTED_DIR* ]]; then
              echo "❌ Unauthorized change detected in: $FILE"
              UNAUTHORIZED_CHANGE=true
            fi
          done

          # If any unauthorized changes are found, exit with an error
          if [ "$UNAUTHORIZED_CHANGE" = true ]; then
            echo "❌ Unauthorized changes to workflow files are not allowed."
            exit 1
          else
            echo "✅ No unauthorized changes detected."
          fi
